const AIR_POLLUTION = "SH.STA.AIRP.P5";
const DISEASE = "SH.DYN.NCOM.ZS";
const HYGIENE = "SH.STA.WASH.P5";
const LIFE_EXPECTANCY = "SP.DYN.LE00.IN";
const POISONING = "SH.STA.POIS.P5";
const SUICIDE = "SH.STA.SUIC.P5";

module.exports = {
  AIR_POLLUTION,
  DISEASE,
  HYGIENE,
  LIFE_EXPECTANCY,
  POISONING,
  SUICIDE
};
