openapi: 3.0.0
info:
  title: World Health Organization API
  description: Serves up healthcare data from the WHO dataset
  version: 0.1.9

servers:
  #uncomment for local dev
  #- url: http://localhost:3000
  #description: Local url
  - url: https://boiling-fjord-16588.herokuapp.com/
    description: Remote url

paths:
  /health/mortality/{region}:
    get:
      operationId: getAllMortalityData
      summary: Returns mortality health data by region
      parameters:
        - in: path
          name: Region of the world
          required: true
          schema:
            $ref: "#/components/parameters/region"
      responses:
        "200": #status code
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mortality"
        "400":
          description: The specified user id is invalid (not a number)
        "404":
          description: A user with the specified id was not found
        default:
          description: Unexpected error

components:
  schemas:
    Mortality:
      properties:
        data:
          type: array
          items:
            type: string
  parameters:
    region:
      type: string
      enum:
        - TEA #east asia & pacific
        - TEC #europe & central asia
        - TLA #latin america & caribbean
        - TMN #middle east & north africa
        - TSA #south asia
        - TSS #sub-saharan africa
        - NAC #north america
