openapi: 3.0.0
info:
  title: World Health Organization API
  description: Serves up healthcare data from the WHO dataset
  version: 0.1.9

servers:
  - url: https://boiling-fjord-16588.herokuapp.com/
    description: Remote production url

paths:
  /health/mortality/{region}:
    get:
      operationId: getRegionalMortalityData
      summary: Returns mortality health data by region
      parameters:
        - in: path
          name: Region of the world
          required: true
          schema:
            $ref: "#/components/parameters/region"
      responses:
        "200": #status code
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mortality"
        "400":
          description: The specified user id is invalid (not a number)
        "404":
          description: A user with the specified id was not found
        default:
          description: Unexpected error

paths:
  /health/nutrition:
    get:
      operationId: getObesityDataByGender
      summary: Returns obesity health data sorted by male/female and highest/lowest
      responses:
        "200": #status code
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Nutrition"
        "400":
          description: The specified user id is invalid (not a number)
        "404":
          description: A user with the specified id was not found
        default:
          description: Unexpected error

components:
  schemas:
    Mortality:
      type: object
      properties:
        country_code:
          type: string
          example: AUS
        items:
          $ref: "#/components/schemas/CountryData"
    CountryData:
      type: object
      properties:
        name:
          type: string
          example: Albania
          description: The name of the country
        disease:
          type: integer
          example: 17
          description: The percentage of deaths in a country from CVD, cancer, diabetes or CRD
        poisoning:
          type: integer
          example: 0.4
          description: The number of deaths per 100,000 in a country due to poisoning
        hygiene:
          type: integer
          example: 0.2
          description: The number of deaths per 100,000 in a country due to unsafe water, sanitation, and lack of hygiene
        lifeExpectancy:
          type: integer
          example: 78.345
          description: The number of years a person can be expected to live for a country
        suicide:
          type: integer
          example: 6.3
          description: The number of deaths per 100,000 in a country due to suicide
        airPollution:
          type: integer
          example: 68
          description: The number of deaths per 100,000 in a country due to air pollution
        lineChart:
          type: object
          properties:
            year:
              type: string
              example: "1960-01-01"
              description: The year of a given life expectancy data point
            value:
              type: integer
              example: 62.279
              description: The number of years of life expectancy for a given year
      Nutrition:
      type: object
      properties:
        highestMale:
          type: array
          items:
            $ref: "#/components/schemas/ObesityData"
        highestFemale:
          type: array
          items:
            $ref: "#/components/schemas/ObesityData"
        lowestMale:
          type: array
          items:
            $ref: "#/components/schemas/ObesityData"
        lowestFemale:
          type: array
          items:
            $ref: "#/components/schemas/ObesityData"
      ObesityData:
        type: object
        properties:
          key: 
            type: string
            example: NRU
            description: The WHO identifiable code for the country
          name:
            type: string
            example: Nauru
            description: The name of the country
          percentage:
            type: integer
            example: 88.3
            description: The percentage of the population of that country that is overweight (either male or female)      
  parameters:
    region:
      type: string
      enum:
        - TEA #east asia & pacific
        - TEC #europe & central asia
        - TLA #latin america & caribbean
        - TMN #middle east & north africa
        - TSA #south asia
        - TSS #sub-saharan africa
        - NAC #north america
